# Generated by Django 4.2.4 on 2023-08-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_remove_vacancy_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.ManyToManyField(related_name='vacancies', to='vacancy.tag'),
        ),
    ]
